branches/urls.py
from django.urls import path
from branches import views

app_name = 'branches'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('create-branch/', views.CreateBranch.as_view(), name='create-branch'),
    path('update-branch/<int:pk>/', views.UpdateBranch.as_view(), name='update-branch'),
    path('delete-branch/<int:pk>', views.DeleteBranch.as_view(), name='delete-branch'),

]

deliveries/urls.py
from django.urls import path
from deliveries import views

app_name = 'deliveries'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('set-supplier/', views.SetSupplier.as_view(), name='set-supplier'),
    path('search-product/', views.SearchProduct.as_view(), name='search-product'),
    path('create-delivery-note/', views.CreateDeliveryNote.as_view(), name='create-delivery-note'),
    path('post-stock/', views.PostStock.as_view(), name='post-stock'),
    path('clear-delivery-note/', views.ClearDeliveryNote.as_view(), name='clear-delivery-note'),
    path('list-delivery-items/<int:delivery_id>/', views.ListDeliveryItems.as_view(), name='list-delivery-items'),
]

home/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    ]
    

pos/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('suppliers/', include('suppliers.urls', namespace='suppliers')),
    path('customers/', include('customers.urls',namespace='customers')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('branches/', include('branches.urls', namespace='branches')),
    path('products/', include('products.urls', namespace='products')),
    path('sales/', include('sales.urls', namespace='sales')),
    path('deliveries/', include('deliveries.urls', namespace='deliveries')),
    path('returns/', include('returns.urls', namespace='returns')),
    path('expense/', include('expesne.urls', namespace='expense')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('create-product/', views.CreateProduct.as_view(), name='create-product'),
    path('update-product/<int:pk>/', views.UpdateProduct.as_view(), name='update-product'),
    path('delete-product/<int:pk>/', views.DeleteProduct.as_view(), name='delete-product'),
    path('product-detail/<int:pk>', views.ProductDetail.as_view(), name='product-detail'),
    path('view-transfers/', views.ViewTransfers.as_view(), name='view-transfers'),
    path('transfer-products/', views.TransferProducts.as_view(), name='transfer-products'),
    path('view-transfer-products/<int:transfer_id>', views.ViewTransferProducts.as_view(), name='view-transfer-products'),
    path('add-product/', views.AddProduct.as_view(), name='add-product'),
    path('delete-cart-product/<int:product_id>/', views.DeleterCartProduct.as_view(), name='delete-cart-product'),
    path('clear-list/', views.ClearList.as_view(), name='clear-list'),
    path('set-transfer-to/', views.SetTransferTo.as_view(), name='set-transfer-to'),
    path('process-transfer/', views.ProcessTransfer.as_view(), name='process-transfer'),
    path('receive-transfer/<int:transfer_id>/', views.ReceiveTransfer.as_view(), name='receive-transfer'),
    path('add-category', views.CreateCategory.as_view(), name='add-categories'),

]

home/models.py
def delivery_value(products_list):

    del_val = 0

    for item in products_list:

        del_val += item['total_cost']

    return del_val

products/models.py
from django.db import models
from suppliers.models import Supplier
from branches.models import Branch
# from deliveries.models import Delivery
from staff.models import Staff

class ProductCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

class TaxPercentage(models.Model):
    tax = models.FloatField(max_length=10 , default=0)  
    date_created = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)


class Product(models.Model):
    STATUS_CHOICES = (  # new
        ("SERVICE", "Service"),
        ("COMSUMABLE", "Consumable")
    )
    status = models.CharField(
        choices=STATUS_CHOICES,
        max_length=100,
        verbose_name="product service",
    )
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(max_length=250, blank=True)
    manufacturer = models.CharField(max_length=150, blank=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT , blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    sku_code = models.CharField(max_length=25, unique=True)
    product_image = models.ImageField(upload_to='product_images', blank=True)
    quantity = models.IntegerField(default=0, help_text="Quantity in stock")
    category = models.ForeignKey(ProductCategory, on_delete=models.PROTECT, null=True, blank=True)
    buying_price = models.FloatField(default=0.0)
    retail_price = models.FloatField(default=0.0)
    wholesale_price = models.FloatField(default=0.0)
   
   
    

    def __str__(self):

        return self.name


class BranchProduct(models.Model):
    """Purposely for keeping track of product quantity at a branch"""

    product = models.ForeignKey(Product, on_delete=models.PROTECT, unique=False,)
    branch = models.ForeignKey(Branch, on_delete=models.PROTECT, unique=False)
    quantity = models.IntegerField(default=0.0)

    def __str__(self):

        return self.product.name


class Transfer(models.Model):
    """A container for products being transfered"""
    transfer_from = models.ForeignKey(Branch, on_delete=models.PROTECT, related_name='transfer_from')
    transfer_to = models.ForeignKey(Branch, on_delete=models.PROTECT, related_name='transfer_to')
    transfer_date = models.DateTimeField(auto_now_add=True)
    date_received = models.DateTimeField(blank=True, null=True)
    received = models.BooleanField(default=False)
    value = models.FloatField(default=0.0)
    staff = models.ForeignKey(Staff, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):

        return str(self.transfer_date)

    def get_products(self):

        """return queryset of products belonging to this transfer"""

        return TransferProduct.objects.filter(transfer=self.pk)

    class Meta:
        permissions = [('receive_transfer', 'Can receive transfer')]


class TransferProduct(models.Model):
    """The individual product instance being transfered"""
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField(default=0)
    transfer = models.ForeignKey(Transfer, on_delete=models.PROTECT)
    unit_cost = models.FloatField(default=0.0)

    def __str__(self):

        return self.product.name

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from suppliers.models import Supplier
from django.contrib.auth.mixins import PermissionRequiredMixin


class Home(PermissionRequiredMixin, TemplateView):

    template_name = 'home.html'
    permission_denied_message = "You dont have permission to access page"

    def has_permission(self):

        if self.request.user.is_staff or self.request.user.is_superuser:

            return True
        else:
            return False

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from datetime import datetime
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import TemplateView, FormView, CreateView, UpdateView, DeleteView, DetailView, ListView
from . models import*
from deliveries.models import Stock, Delivery
from suppliers.models import Supplier
from .forms import*
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist


class ReceiveTransfer(PermissionRequiredMixin, TemplateView):
    permission_required = ['transfer.receive_transfer']
    raise_exception = True
    permission_denied_message = "You dont have permission to receive transfer"
    template_name = 'products/receive_transfer.html'

    def get(self, request, *args, **kwargs):

        context = dict()

        transfer = get_object_or_404(Transfer, pk=self.kwargs['transfer_id'])
        transfer_products = TransferProduct.objects.filter(transfer_id=self.kwargs['transfer_id'])

        context['transfer_products'] = transfer_products
        context['transfer'] = transfer

        if request.GET.get("type") == "as_is":

            if transfer.received:  # Prevent repeat if page is reloaded
                return redirect(to=f"/products/receive_transfer/{transfer.pk}/")

            # Add entry in deliveries
            received_from = get_object_or_404(Supplier, name=transfer.transfer_from.name)
            delivery = Delivery(
                received_from_id=received_from.pk,
                value=transfer.value,
                processed_by_id=request.user.pk,
                delivery_number="TRANSFER",
                is_transfer=True,
                branch_id=request.user.branch_id
            )
            delivery.save()

            for product in transfer_products:

                branch_product, created = BranchProduct.objects.get_or_create(
                    product_id=product.pk,
                    branch_id=transfer.transfer_to.pk
                )

                branch_product.quantity = branch_product.quantity + product.quantity

                branch_product.save()

                # create stock instance
                product_details = get_object_or_404(Stock, product_id=product.product_id, current_branch_id=transfer.transfer_from_id)
                stock = Stock(
                    quantity=product.quantity,
                    buying_price=product_details.buying_price,
                    retail_price=product_details.retail_price,
                    wholesale_price=product_details.wholesale_price,
                    current_branch_id=request.user.branch_id,
                    delivery_id=delivery.pk,
                    home_branch_id=request.user.branch_id,
                    product_id=product.product_id,
                    staff_id=request.user.pk
                )
                stock.save()

            transfer.received = True
            transfer.date_received = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            transfer.save()

            messages.success(request, "Success, items have been received", extra_tags="alert alert-success")

        return render(request, self.template_name, context=context)


class ViewTransferProducts(PermissionRequiredMixin, TemplateView):
    permission_required = ['transfer.view_transfer']
    permission_denied_message = "You dont have permission to view transfers"
    raise_exception = True
    template_name = "products/view_transfer_items.html"
    context_object_name = "transfer_products"

    def get(self, request, *args, **kwargs):

        context = dict()

        transfer = get_object_or_404(Transfer, pk=self.kwargs['transfer_id'])

        context['transfer'] = transfer

        context['transfer_products'] = transfer.get_products()

        return render(request, self.template_name, context=context)


class ProcessTransfer(PermissionRequiredMixin, FormView):
    permission_required = ['transfer.add_transfer']
    permission_denied_message = "You dont have permission to add transfers"
    raise_exception = True
    template_name = 'products/transfer_products.html'
    form_class = ProductTransferForm

    def get(self, request, *args, **kwargs):

        if "products" not in request.session.keys():
            return redirect(to='/products/view-transfers/')

        list_products = request.session['products']

        transfer = Transfer(
            transfer_from_id=request.user.branch_id,
            transfer_to_id=request.session['transfer_to_id'],
            staff_id=request.user.pk,
        )

        transfer.save()

        value = 0.0

        for product in list_products:

            item = Stock.objects.filter(
                product_id=product['product_id'],
                home_branch_id=request.user.branch_id
            ).last()

            # Update Product model
            product_instance = get_object_or_404(Product, pk=product['product_id'])
            product_instance.quantity -= product['quantity']
            product_instance.save()

            # Update transfer_product tbl
            transfer_product = TransferProduct(
                transfer_id=transfer.pk,
                product_id=product['product_id'],
                unit_cost=item.buying_price,
                quantity=product['quantity']
            )

            transfer_product.save()
            value += product['quantity'] * item.buying_price

            # Update branch_stock tbl
            branch_stock = BranchProduct.objects.get(
                branch_id=request.user.branch_id,
                product_id=product['product_id']
            )

            branch_stock.quantity -= product['quantity']
            branch_stock.save()

        transfer.value = value
        transfer.save()

        del request.session['products']
        del request.session['transfer_to_id']

        return redirect(to='/products/view-transfers/')


class ViewTransfers(PermissionRequiredMixin, ListView):
    permission_required = ['transfer.view_transfer']
    permission_denied_message = "You dont have permission to view transfers"
    raise_exception = True
    template_name = 'products/view_transfers.html'
    form_class = TransferFiltersForm
    context_object_name = "transfers_list"

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)

        context['form'] = self.form_class

        return context

    def get_queryset(self):

        q = Transfer.objects.all()
        # q = Transfer.objects.filter(transfer_from_id=self.request.user.branch_id)

        return q


class AddProduct(PermissionRequiredMixin, FormView):
    """Add product item to session cart"""
    permission_required = ['transfer.add_transfer']
    permission_denied_message = "You dont have permission to add transfers"
    raise_exception = True
    template_name = 'products/transfer_products.html'
    form_class = ProductTransferForm

    def post(self, request, *args, **kwargs):

        form = self.form_class(data=request.POST)

        if form.is_valid():

            product = get_object_or_404(Product, pk=form.cleaned_data['product'])

            try:
                stock = Stock.objects.filter(
                    product_id=product.pk,
                    home_branch_id=request.user.branch_id,
                    current_branch_id=request.user.branch_id
                ).latest('posted')

            except ObjectDoesNotExist:

                messages.error(request, "Out of stock, no purchases on record", extra_tags="alert alert-danger")

                return redirect(to='/products/transfer-products/')

            if stock.quantity < form.cleaned_data['quantity']:

                messages.error(
                    request,
                    f"Out of range, only {stock.quantity} available.",
                    extra_tags="alert alert-danger"
                )

                return redirect(to='/products/transfer-products/')

            new_product = {
                'product_name': product.name,
                'product_id': product.pk,
                'unit_cost': stock.buying_price,
                'quantity': form.cleaned_data['quantity'],
                'total': form.cleaned_data['quantity'] * stock.buying_price,
            }

            if "products" not in request.session:  # first product

                request.session['products'] = list()

                request.session['products'].append(new_product)

                request.session['products_total'] = new_product['total']

            else:

                cart_products = request.session['products']
                product_ids = [pk['product_id'] for pk in cart_products]

                if new_product['product_id'] not in product_ids:

                    cart_products.append(new_product)

                else:

                    for item in cart_products:

                        if item['product_id'] == new_product['product_id']:

                            item['quantity'] = item['quantity'] + new_product['quantity']
                            item['total'] = item['quantity'] * item['unit_cost']

                        else:
                            pass

                request.session['products'] = cart_products
                request.session['products_total'] = sum([item['total'] for item in cart_products])

        return redirect(to='/products/transfer-products/')


class TransferProducts(PermissionRequiredMixin, FormView):

    """Only displays the template ie form and list"""

    permission_required = ['transfer.add_transfer']
    raise_exception = True
    permission_denied_message = "You dont have permission to add transfers"
    template_name = 'products/transfer_products.html'
    form_class = ProductTransferForm

    def get(self, request, *args, **kwargs):

        if "transfer_to_id" not in self.request.session.keys():

templates/products/edit_product.html
{% extends 'base.html' %}
{% block title %}Update Product{% endblock title %}
{% block page_content %}
    <nav class="navbar navbar-expand-lg context-bar">
        <a class="navbar-brand" href="#">
            <i class="fa fa-shopping-basket"></i> Products
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{% url 'products:create-product' %}">
              <i class="fa fa-plus-circle"></i> Add New
            </a>
            <a class="nav-item nav-link" href="{% url 'products:delete-product' pk=product.pk %}">
              <i class="fa fa-trash"></i> Delete
            </a>
            <a class="nav-item nav-link" href="{% url 'products:home' %}">
              <i class="fa fa-list"></i> View
            </a>
        </div>
      </div>
    </nav>

    {% include 'messages.html' %}

    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h5 class="">Edit {{ product.name }}</h5>
                </div>
                <div class="card-body">
                    <form action="{% url 'products:update-product' pk=product.pk %}" method="post">{% csrf_token %}

                        {{ form.as_p }}

                        <button type="submit" class="btn btn-info btn-block">Update</button>
                    </form>

                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="">{{ product }}</h5>
                </div>
                <div class="card-body">
                    {% if product %}
                        <table class="table table-striped table-bordered table-hover table-condensed">
                            <tbody>
                                <tr>
                                    <td>Name </td>
                                    <td>
                                        <a href="{% url 'products:product-detail' pk=product.pk %}"> {{ product.name }}</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Sku code</td>
                                    <td>{{ product.sku_code }}</td>
                                </tr>
                                <tr>
                                    <td>Manufacturer</td>
                                    <td>{{ product.manufacturer }}</td>
                                </tr>
                                <tr>
                                    <td>Supplier</td>
                                    <td>{{ product.supplier }}</td>
                                </tr>
                                <tr>
                                    <td>Description</td>
                                    <td>{{ product.description }}</td>
                                </tr>
                            </tbody>
                        </table>
                    {% else %}
                        <div class="alert alert-info">No products have been added yet</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>





{% endblock page_content %}

templates/products/product_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete Product{% endblock title %}
{% block page_content %}
    <nav class="navbar navbar-expand-lg context-bar">
      <a class="navbar-brand" href="#"> <i class="fa fa-shopping-basket"></i> Products</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{% url 'products:update-product' pk=product.pk %}">
              <i class="fa fa-edit"></i> Edit
          </a>
          <a class="nav-item nav-link" href="{% url 'products:create-product' %}">
              <i class="fa fa-plus-circle"></i> Add New
          </a>

            <a class="nav-item nav-link" href="{% url 'products:home' %}">
              <i class="fa fa-list"></i> View
            </a>
        </div>
      </div>
    </nav>

    {% include 'messages.html' %}

    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h5 class="">Delete {{ product.name }}</h5>
                </div>
                <div class="card-body">
                    <h5 class="text-danger">Proceed to delete {{ product.name }} ?</h5>
                    <form action="{% url 'products:delete-product' pk=product.pk %}" method="post">{% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-block">Delete</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="">{{ supplier.name }} Details</h5>
                </div>
                <div class="card-body">
                    {% if supplier %}
                        <table class="table table-hover table-striped table-responsive">
                            <tbody>
                                <tr><td>Name</td><td>{{ supplier.name }}</td></tr>
                                <tr><td>Phone</td><td>{{ supplier.primary_phone }}</td></tr>
                                <tr><td>Secondary Phone</td><td>{{ supplier.secondary_phone }}</td></tr>
                                <tr><td>Email</td><td>{{ supplier.email }}</td></tr>
                                <tr><td>Additional email</td><td>{{ supplier.additional_email }}</td></tr>
                                <tr><td>Address</td><td>{{ supplier.address }}</td></tr>
                                <tr><td>Additional Address</td><td>{{ supplier.additional_address }}</td></tr>
                                <tr><td>Created</td><td>{{ supplier.date_created|date:'d-m-Y H:i' }}</td></tr>
                            </tbody>
                        </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>





{% endblock page_content %}

templates/products/transfer_products.html
{% extends 'base.html' %}

{% block title %}Transfer Products{% endblock title %}

{% load static %}
{% block page_style %}
    <link href="{% static 'autocomplete/easy-autocomplete.min.css' %}" rel="stylesheet" type="text/css">
    <style>
        th{background-color: rgb(233, 236, 239);}
    </style>
{% endblock page_style %}
{% block page_js %}
    <script src="{% static 'autocomplete/jquery-1.11.2.min.js' %}"></script>
	<script src="{% static 'autocomplete/jquery.easy-autocomplete.min.js' %}" type="text/javascript" ></script>
    <script>
    $(document).ready(function () {

        $('#date_from').datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd-mm-yy'
        });
        $('#date_to' ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd-mm-yy'
        });
    });

    </script>
{% endblock page_js %}

{% block page_content %}
    <nav class="navbar navbar-expand-lg context-bar">
      <a class="navbar-brand" href="#">
          <i class="fa fa-truck"></i> Transfer Stock to {{ request.session.transfer_to }}
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{% url 'products:view-transfers' %}">
              <i class="fa fa-plus-circle"></i> View Transfers
          </a>
        </div>
      </div>
    </nav>
    {% include 'messages.html' %}

    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post" action="{% url 'products:add-product' %}">{% csrf_token %}
                        {{ form.as_p }}
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-default btn-block">
                                    Add <i class="fa fa-plus"></i>
                                </button>
                            </div>
                            <div class="col">

                            </div>
                            <div class="col">
                                <button type="reset" class="btn btn-default btn-block">
                                    Reset <i class="fa fa-remove"></i>
                                </button>
                            </div>
                        </div>
                        <p class="mt-3">
                            <a href="{% url 'products:set-transfer-to' %}" class="btn btn-info btn-block">
                                Change branch to <i class="fa fa-edit"></i>
                            </a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-body">
                    {% if request.session.products|length > 0 %}

                        <table class="table table-striped table-responsive table-bordered table-sm">
                            <thead>
                                <th class="text-center"><i class="fa fa-remove"></i> </th>
                                <th>Item</th>
                                <th class="text-center">Qty</th>
                                <th class="text-center">Unit cost</th>
                                <th class="text-center">Total</th>
                            </thead>
                            {% for product in request.session.products %}
                                <tr>
                                    <td class="text-center">
                                        <a href="{% url 'products:delete-cart-product' product_id=product.product_id %}">
                                            <i class="fa fa-trash text-danger"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'products:product-detail' pk=product.product_id %}">{{ product.product_name }}</a>
                                    </td>
                                    <td class="text-center">{{ product.quantity }}</td>
                                    <td class="text-center">{{ product.unit_cost }}</td>
                                    <td class="text-center">{{ product.total }}</td>
                                </tr>
                            {% endfor %}
                        </table>

                        <div class="row">
                            <div class="col-3">
                                <a href="{% url 'products:process-transfer' %}" class="btn btn-info">Submit <i class="fa fa-send"> </i></a>
                            </div>
                            <div class="col-3"></div>
                            <div class="col-3">
                                <a href="{% url 'products:clear-list' %}" class="btn btn-light">
                                    Clear list <i class="fa fa-eraser text-danger"></i>
                                </a>
                            </div>
                            <div class="col-3">
                                <a href="" class="btn btn-light">
                                    Total {{ request.session.products_total }}
                                </a>
                            </div>
                        </div>
                    {% else %}
                        <div class="alert alert-info">No items in list</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <script>
        let options = {

            url: "{% url 'deliveries:search-product' %}?product=" + $("#product_id").val(),

            getValue: "product_name",

            template: {
                type: "description",
                fields: {
                    description: "product_name"
                }
            },

            list: {
                match: {enabled: true,},
                onChooseEvent: function() {
                    let product_name = $("#product_id").getSelectedItemData().product_name;
                    let product_id = $("#product_id").getSelectedItemData().product_id;

                    $("input#product_id").val(product_id);
                    $("input#product_id").attr("readonly", true);

                    $("label[for='product_id']").html("Product: <strong style='color: black;'>"+product_name+"</strong>");
                }
            },

            theme: "plate-dark"
        };

        $("#product_id").easyAutocomplete(options);
    </script>

{% endblock page_content %}