customers/urls.py
from django.urls import path
from customers import views

app_name = 'customers'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('add-new/', views.CreateCustomer.as_view(), name='create-customer'),
    path('update-customer/<int:pk>', views.UpdateCustomer.as_view(), name='update-customer'),
    path('delete-customer/<int:pk>', views.DeleteCustomer.as_view(), name='delete-customer'),
]

home/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    ]
    

pos/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('suppliers/', include('suppliers.urls', namespace='suppliers')),
    path('customers/', include('customers.urls',namespace='customers')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('branches/', include('branches.urls', namespace='branches')),
    path('products/', include('products.urls', namespace='products')),
    path('sales/', include('sales.urls', namespace='sales')),
    path('deliveries/', include('deliveries.urls', namespace='deliveries')),
    path('returns/', include('returns.urls', namespace='returns')),
    path('expense/', include('expesne.urls', namespace='expense')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('create-staff/', views.CreateStaff.as_view(), name='create-staff'),
    path('update-staff/<int:pk>/', views.UpdateStaff.as_view(), name='update-staff'),
    path('change-branch/', views.ChangeBranch.as_view(), name='change-branch'),
    path('update-password/<int:pk>/', views.UpdatePassword.as_view(), name='update-password'),
    path('set-permissions/<int:pk>/', views.SetPermissions.as_view(), name='set-permissions'),
    path('delete-staff/<int:pk>/', views.DeleteStaff.as_view(), name='delete-staff'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

customers/models.py
from django.db import models


class Customer(models.Model):
    name = models.CharField(max_length=250)
    phone = models.CharField(max_length=15)
    tin_number = models.CharField(max_length=100, blank=True)
    vrn_number = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=50, blank=True)
    address = models.TextField(max_length=50)
    date_created = models.DateTimeField(auto_created=True, auto_now_add=True)

    class Meta:
        # Table's name
        db_table = "Customer"
        verbose_name_plural = "Customer"

    def __str__(self):
        return self.name

home/models.py
def delivery_value(products_list):

    del_val = 0

    for item in products_list:

        del_val += item['total_cost']

    return del_val

customers/forms.py
from django import forms
from customers.models import Customer


class UpdateCustomerForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone'].widget.attrs.update({'class': 'form-control'})
        self.fields['tin_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['vrn_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'rows': 1})

    class Meta:
        model = Customer
        exclude = ['date_created']


class CreateCustomerForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone'].widget.attrs.update({'class': 'form-control'})
        self.fields['tin_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['vrn_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'rows': 1})

    class Meta:
        model = Customer
        exclude = ['date_created']

customers/views.py
from customers.models import Customer
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib import messages
from customers.forms import CreateCustomerForm, UpdateCustomerForm


class Home(PermissionRequiredMixin, ListView):
    template_name = 'customers/home.html'
    permission_required = ['customers.view_customer']
    raise_exception = True
    permission_denied_message = "You dont have permission to view customers"
    context_object_name = 'customers'
    model = Customer

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)

        customers_list = Customer.objects.all().order_by('-pk')[:10]

        customers = []
        num = 0

        for customer in customers_list:

            num = num + 1

            customers.append({
                'num': num,
                'pk': customer.pk,
                'name': customer.name,
                'phone': customer.phone,
                'tin_number': customer.tin_number,
                'vrn_number': customer.vrn_number,
                'email': customer.email
            })

        context['customers'] = customers

        return context


class CreateCustomer(PermissionRequiredMixin, CreateView):
    permission_required = ['customers.add_customer']
    raise_exception = True
    permission_denied_message = "You dont have permission to add customers"
    model = Customer
    template_name = 'customers/create_customer.html'
    form_class = CreateCustomerForm

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        customers_list = Customer.objects.all().order_by('-pk')[:10]

        customers = []
        num = 0

        for customer in customers_list:
            num = num + 1

            customers.append({
                'num': num,
                'pk': customer.pk,
                'name': customer.name,
                'phone': customer.phone,
                'email': customer.email
            })

        context['customers'] = customers

        return context

    def get_success_url(self):

        messages.success(self.request, 'Success, new customer created', extra_tags='alert alert-success')

        return reverse_lazy('customers:create-customer')


class UpdateCustomer(PermissionRequiredMixin, UpdateView):
    permission_required = ['customers.change_customer']
    raise_exception = True
    permission_denied_message = "You dont have permission to change customers"
    template_name = 'customers/edit_customer.html'
    model = Customer
    form_class = UpdateCustomerForm

    def get_success_url(self):

        messages.success(self.request, 'Success, customer details updated', extra_tags='alert alert-success')

        return reverse_lazy(viewname='customers:update-customer', kwargs={'pk': self.kwargs['pk']})


class DeleteCustomer(PermissionRequiredMixin, DeleteView):
    permission_required = ['customers.delete_customer']
    raise_exception = True
    permission_denied_message = "You dont have permission to delete customers"
    model = Customer
    context_object_name = 'customer'

    def get_success_url(self):

        messages.success(self.request, 'Success, customer has been deleted', extra_tags='alert alert-success')

        return reverse_lazy(viewname='customers:home')

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from suppliers.models import Supplier
from django.contrib.auth.mixins import PermissionRequiredMixin


class Home(PermissionRequiredMixin, TemplateView):

    template_name = 'home.html'
    permission_denied_message = "You dont have permission to access page"

    def has_permission(self):

        if self.request.user.is_staff or self.request.user.is_superuser:

            return True
        else:
            return False

templates/customers/create_customer.html
{% extends 'base.html' %}
{% block title %}Create Customer{% endblock title %}
{% block page_content %}
    <nav class="navbar navbar-expand-lg context-bar">
      <a class="navbar-brand" href="#">
          <i class="fa fa-handshake"></i> Customers
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{% url 'customers:home' %}">
              <i class="fa fa-list"></i> View</a>
        </div>
      </div>
    </nav>

    {% include 'messages.html' %}

    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h5 class="">Add New Customer</h5>
                </div>
                <div class="card-body">

                    <form action="{% url 'customers:create-customer' %}" method="post">{% csrf_token %}

                        {{ form.as_p }}

                        <button type="submit" class="btn btn-info btn-block">Save</button>
                    </form>

                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="">Most Recent Customers</h5>
                </div>
                <div class="card-body">

                    {% if customers|length > 0 %}
                        <table class="table table-striped table-bordered table-hover table-condensed">
                            <thead>
                                <th>#</th><th>Name</th><th>Phone</th><th>Email</th>
                            </thead>
                            <tbody>
                                {% for customer in customers %}
                                    <tr>
                                        <td>{{ customer.num }}.</td>
                                        <td>
                                            <a href="{% url 'customers:update-customer' pk=customer.pk %}"> {{ customer.name }}</a>
                                        </td>
                                        <td>{{ customer.phone }}</td>
                                        <td>{{ customer.email }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <div class="alert alert-info">No customers have been added yet</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>





{% endblock page_content %}

templates/customers/customer_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete Customer{% endblock title %}
{% block page_content %}
    <nav class="navbar navbar-expand-lg context-bar">
      <a class="navbar-brand" href="#"> <i class="fa fa-handshake"></i> Customers</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">

            <a class="nav-item nav-link" href="{% url 'customers:update-customer' pk=customer.pk %}">
              <i class="fa fa-edit"></i> Edit
            </a>
          <a class="nav-item nav-link" href="{% url 'customers:create-customer' %}">
              <i class="fa fa-plus-circle"></i> Add New
          </a>
            <a class="nav-item nav-link" href="{% url 'customers:home' %}">
              <i class="fa fa-list"></i> View
            </a>
        </div>
      </div>
    </nav>

    {% include 'messages.html' %}

    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h5 class="">Delete {{ customer.name }}</h5>
                </div>
                <div class="card-body">
                    <h5 class="text-danger">Proceed to delete {{ customer.name }} ?</h5>
                    <form action="{% url 'customers:delete-customer' pk=customer.pk %}" method="post">{% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-block">Delete</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="">{{ customer.name }}'s Details</h5>
                </div>
                <div class="card-body">
                    <table class="table table-hover table-striped table-responsive">
                        <tbody>
                            <tr><td>Name</td><td>{{ customer.name }}</td></tr>
                            <tr><td>Phone</td><td>{{ customer.primary_phone }}</td></tr>
                            <tr><td>Email</td><td>{{ customer.email }}</td></tr>
                            <tr><td>Created</td><td>{{ customer.date_created|date:'d-m-Y H:i' }}</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>





{% endblock page_content %}

templates/customers/edit_customer.html
{% extends 'base.html' %}
{% block title %}Update Customer{% endblock %}
{% block page_content %}
    <nav class="navbar navbar-expand-lg context-bar">
      <a class="navbar-brand" href="#"> <i class="fa fa-handshake"></i> Customers</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">

          <a class="nav-item nav-link" href="{% url 'customers:create-customer' %}">
              <i class="fa fa-plus-circle"></i> Add New
          </a>
            <a class="nav-item nav-link" href="{% url 'customers:home' %}">
              <i class="fa fa-list"></i> View
            </a>
          <a class="nav-item nav-link" href="{% url 'customers:delete-customer' pk=customer.pk %}">
              <i class="fa fa-trash"></i> Delete</a>
        </div>
      </div>
    </nav>

    {% include 'messages.html' %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h5 class="">Update {{ customer.name }}</h5>
                </div>
                <div class="card-body">
                    <form action="{% url 'customers:update-customer' pk=customer.pk %}" method="post">{% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-info btn-block">Update</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="">{{ customer.name }} Details</h5>
                </div>
                <div class="card-body">
                    <table class="table table-hover table-striped table-responsive">
                        <tbody>
                            <tr><td>Name</td><td>{{ customer.name }}</td></tr>
                            <tr><td>Description</td><td>{{ customer.description }}</td></tr>
                            <tr><td>Primary phone</td><td>{{ customer.primary_phone }}</td></tr>
                            <tr><td>Secondary phone</td><td>{{ customer.secondary_phone }}</td></tr>
                            <tr><td>Email</td><td>{{ customer.email }}</td></tr>
                            <tr><td>Additional email</td><td>{{ customer.additional_email }}</td></tr>
                            <tr><td>Address</td><td>{{ customer.address }}</td></tr>
                            <tr><td>Additional address</td><td>{{ customer.additional_address }}</td></tr>
                            <tr><td>Created</td><td>{{ customer.date_created|date:'d-m-Y H:i' }}</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock page_content %}

templates/customers/home.html
{% extends 'base.html' %}
{% block title %}Customers{% endblock title %}
{% block page_content %}
    <nav class="navbar navbar-expand-lg context-bar">
      <a class="navbar-brand" href="#">
          <i class="fa fa-handshake"></i> Customers
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{% url 'customers:create-customer' %}">
              <i class="fa fa-plus-circle"></i> Add New
          </a>
        </div>
      </div>
    </nav>

    {% include 'messages.html' %}

    <div class="card ">
        <div class="card-body">
            {% if customers|length > 0 %}

                <table class="table table-striped table-bordered table-hover table-condensed" id="myTable">
                    <thead>
                        <th>#</th><th>Name</th><th>TIN</th><th>VRN</th><th>Phone</th><th>Email</th>
                    </thead>
                    <tbody>
                        {% for customer in customers %}
                            <tr>
                                <td>{{ customer.num }}.</td>
                                <td>
                                    <a href="{% url 'customers:update-customer' pk=customer.pk %}"> {{ customer.name }}</a>
                                </td>
                                <td>{{ customer.tin_number }}</td>
                                <td>{{ customer.vrn_number }}</td>
                                <td>{{ customer.phone }}</td>
                                <td>{{ customer.email }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div class="alert alert-info">No customers have been added yet</div>
            {% endif %}
        </div>
    </div>


{% endblock page_content %}

templates/customers/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Login{% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap-4/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'datatables/datatables.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/media-queries.css' %}">
    <script src="{% static 'jquery-3/jquery-3.3.1.slim.min.js' %}"></script>
    <script defer src="{% static 'bootstrap-4/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap-4/js/bootstrap.min.js' %}"></script>
    <script defer src="{% static 'fontawesome-5/js/fontawesome-all.min.js' %}"></script>
    <script defer src="{% static 'fontawesome-5/js/fa-v4-shims.min.js' %}"></script>
    <script defer src="{% static 'datatables/datatables.min.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#id_username').attr('class', 'form-control');
            $('#id_password').attr('class', 'form-control');
        });
    </script>
    <style type="text/css">
        #login-form{
            max-width: 350px;
            padding: 12px;
            box-shadow:  0 2px 2px 0 rgba(0,0,0,0.14),0 1px 5px 0 rgba(0,0,0,0.12),0 3px 1px -2px rgba(0,0,0,0.2);;
            margin: 30px auto 10px auto;
            border-radius: 6px;
            background: #fff;
        }
        #login-form label{
            color: crimson;
            font-size: 12pt;
            margin-bottom: 10px;
            padding-left: 1px;
        }
        #login-form div{
            margin-bottom: 15px;
        }
        #login-form form{
            background: #eee;
            padding: 12px;
            border-radius: 5px;
        }
        label{padding-left: 0px;}
    </style>
</head>
<body>
    <div class="container">
    <div id="login-form">
        <form method="post" action="{% url 'staff:login' %}?next={{ next }}">{% csrf_token %}
        <p class="text-center bg-danger text-white p-4">
            <a href="{% url 'home' %}">BS POS</a>
        </p>
            {% include 'messages.html' %}
            {% block form_el %}
            <label class="label">Username</label>
            <div class="">{{ form.username }}</div>

            <label class="label">{{ form.password.label }}</label>
            <div class="">{{ form.password }}</div>
            <p class="text-right">
                <button type="submit" class="btn btn-info">Login</button>
            </p>
            {% endblock form_el %}


        </form>
        <p class="text-right mt-3">
            Forgot password? <a href="#" >Click here</a>
        </p>
    </div><!-- .row -->
</div>
</body>
</html>

templates/customers/staff_confirm_delete.html
{% extends 'base.html' %}
{% block page_content %}
    <nav class="navbar navbar-expand-lg context-bar">
      <a class="navbar-brand" href="#"> <i class="fa fa-briefcase"></i> Staff</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">

          <a class="nav-item nav-link" href="{% url 'staff:create-staff' %}">
              <i class="fa fa-plus-circle"></i> Add New
          </a>
            <a class="nav-item nav-link" href="{% url 'staff:home' %}">
              <i class="fa fa-list"></i> View
            </a>
        </div>
      </div>
    </nav>

    {% include 'messages.html' %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h5 class="">Delete Staff {{ staff.get_full_name }}</h5>
                </div>
                <div class="card-body">
                    <h5 class="text-danger">Proceed to delete {{ staff.get_full_name }} ?</h5>
                    <form action="{% url 'staff:delete-staff' pk=staff.pk %}" method="post">{% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-block">Delete</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="">{{ staff.get_full_name }} Details</h5>
                </div>
                <div class="card-body">
                    <table class="table table-hover table-striped table-responsive">
                        <tbody>
                            <tr><td>Name</td><td>{{ staff.get_full_name }}</td></tr>
                            <tr><td>Phone</td><td>{{ staff.phone_number }}</td></tr>
                            <tr><td>Email</td><td>{{ staff.email }}</td></tr>
                            <tr><td>Created</td><td>{{ staff.date_joined|date:'d-m-Y H:i' }}</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>





{% endblock page_content %}