expesne/urls.py
from django.urls import path
from expesne import views

app_name = 'expense'

urlpatterns = [
    path('expense/', views.ListExpense, name='expesne'),
    path('add_expense/', views.CreateExpense, name='add-expesne'),
    path('expense-report', views.ExpenseReportsHome.as_view(), name="expense-report"),
    path('profit-loss-report', views.ProfitLossReportsHome.as_view(), name="profit-loss-report"),

]

home/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    ]
    

pos/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('suppliers/', include('suppliers.urls', namespace='suppliers')),
    path('customers/', include('customers.urls',namespace='customers')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('branches/', include('branches.urls', namespace='branches')),
    path('products/', include('products.urls', namespace='products')),
    path('sales/', include('sales.urls', namespace='sales')),
    path('deliveries/', include('deliveries.urls', namespace='deliveries')),
    path('returns/', include('returns.urls', namespace='returns')),
    path('expense/', include('expesne.urls', namespace='expense')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('create-product/', views.CreateProduct.as_view(), name='create-product'),
    path('update-product/<int:pk>/', views.UpdateProduct.as_view(), name='update-product'),
    path('delete-product/<int:pk>/', views.DeleteProduct.as_view(), name='delete-product'),
    path('product-detail/<int:pk>', views.ProductDetail.as_view(), name='product-detail'),
    path('view-transfers/', views.ViewTransfers.as_view(), name='view-transfers'),
    path('transfer-products/', views.TransferProducts.as_view(), name='transfer-products'),
    path('view-transfer-products/<int:transfer_id>', views.ViewTransferProducts.as_view(), name='view-transfer-products'),
    path('add-product/', views.AddProduct.as_view(), name='add-product'),
    path('delete-cart-product/<int:product_id>/', views.DeleterCartProduct.as_view(), name='delete-cart-product'),
    path('clear-list/', views.ClearList.as_view(), name='clear-list'),
    path('set-transfer-to/', views.SetTransferTo.as_view(), name='set-transfer-to'),
    path('process-transfer/', views.ProcessTransfer.as_view(), name='process-transfer'),
    path('receive-transfer/<int:transfer_id>/', views.ReceiveTransfer.as_view(), name='receive-transfer'),
    path('add-category', views.CreateCategory.as_view(), name='add-categories'),

]

sales/urls.py
from django.urls import path
from sales import views

app_name = 'sales'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('search-products', views.SearchProducts.as_view(), name='search-products'),
    path('add-to-cart', views.AddToCart.as_view(), name='add-to-cart'),
    path('clear-cart', views.ClearCart.as_view(), name='clear-cart'),
    path('delete-from-cart/<int:product_id>/', views.DeleteCartProduct.as_view(), name='delete-from-cart'),
    path('check-out/', views.CheckOut.as_view(), name='check-out'),
    path('reports-home/', views.ReportsHome.as_view(), name='reports-home'),
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('create-staff/', views.CreateStaff.as_view(), name='create-staff'),
    path('update-staff/<int:pk>/', views.UpdateStaff.as_view(), name='update-staff'),
    path('change-branch/', views.ChangeBranch.as_view(), name='change-branch'),
    path('update-password/<int:pk>/', views.UpdatePassword.as_view(), name='update-password'),
    path('set-permissions/<int:pk>/', views.SetPermissions.as_view(), name='set-permissions'),
    path('delete-staff/<int:pk>/', views.DeleteStaff.as_view(), name='delete-staff'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

home/models.py
def delivery_value(products_list):

    del_val = 0

    for item in products_list:

        del_val += item['total_cost']

    return del_val

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from suppliers.models import Supplier
from django.contrib.auth.mixins import PermissionRequiredMixin


class Home(PermissionRequiredMixin, TemplateView):

    template_name = 'home.html'
    permission_denied_message = "You dont have permission to access page"

    def has_permission(self):

        if self.request.user.is_staff or self.request.user.is_superuser:

            return True
        else:
            return False

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SUPERCOM POS :: {% block title %} {% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" href="{% static 'jquery-ui-1.12/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-4/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'datatables/datatables.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/media-queries.css' %}">

    <script src="{% static 'jquery-ui-1.12/external/jquery/jquery.js' %}"></script>
    <script src="{% static 'jquery-ui-1.12/jquery-ui.min.js' %}"></script>
    <script src="{% static 'bootstrap-4/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/script.js' %}"></script>

    <script defer src="{% static 'fontawesome-5/js/fontawesome-all.min.js' %}"></script>
    <script defer src="{% static 'fontawesome-5/js/fa-v4-shims.min.js' %}"></script>
    <script defer src="{% static 'datatables/datatables.min.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#myTable').DataTable( {
                dom: 'Bfrtip',
                "pageLength": 50,
                buttons: [
                    'copy', 'excel', {
                        extend: 'pdfHtml5',
                        customize: function ( doc ) {
                            doc.content.splice( 1, 0, {} );
                        }
                    }, 'print'
                ]
            } );

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });

            $('#id_old_password').attr('class', 'form-control');
            $('#id_new_password1').attr('class', 'form-control');
            $('#id_new_password2').attr('class', 'form-control');

        });
    </script>
{% block page_style %}{% endblock page_style %}
{% block page_js %}{% endblock page_js %}

</head>
<body>
    <div class="wrapper">
    <!-- Sidebar  -->
    {% include 'sidebar.html' %}
    <!-- Page Content  -->

    <div id="content" class="container-fluid">
        <!-- Load top nav here -->
        {% include 'top-navigation.html' %}
        <div class="content p-4">
            {% block page_content %}{% endblock page_content %}
        </div>

    </div>
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %} Home{% endblock title %}
{% load static %}
{% block page_style %}
		<link href="{% static 'autocomplete/easy-autocomplete.min.css' %}" rel="stylesheet" type="text/css">
        <style>
            th{background-color: rgb(233, 236, 239);}
            .fa-trash-alt, .fa-trash{color: red;}
        </style>
{% endblock page_style %}
{% block page_js %}
		<script src="{% static 'autocomplete/jquery-1.11.2.min.js' %}"></script>
		<script src="{% static 'autocomplete/jquery.easy-autocomplete.min.js' %}" type="text/javascript" ></script>
{% endblock page_js %}

{% block page_content %}
    {% include 'messages.html' %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <input id="product-search" class="form-control" />
                </div>
            </div>
            <div class="card mt-3">
                <div class="card-body text-center">
                    <div id="product-details">
                        <form style="display: none;" id="sales_form" >{% csrf_token %}
                            <h4 id="product_name" class="bg-dark text-white pt-2 pb-2 mb-0"></h4>
                            <table class="table table-bordered">
                                <thead class="bg-light">
                                    <th>Price</th><th>Qty</th><th>Tax</th><th>Total</th>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><input class="form-control" name="unit_price" id="unit_price"></td>
                                        <td><input type="number" min="1" class="form-control" name="quantity" id="quantity"></td>
                                        <td><input type="number" min="0" class="form-control" name="tax" id="tax"></td>
                                        <td><input class="form-control" name="total" id="total"></td>
                                    </tr>
                                </tbody>
                            </table>
                            <input type="hidden" name="product_name" id="product">
                            <input type="hidden" name="product_id" id="product_pk">
                            <button class="btn btn-info justify-content-end" type="submit">
                                Add to Cart <i class="fa fa-cart-plus"></i>
                            </button>
                        </form>
                    </div>
                    <p class="small" id="search-instructions">Search products to start selling</p>
                </div>
            </div>

        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-8">
                            <h4 class="card-title mb-0"><i class="fa fa-shopping-cart"></i> Shopping Cart</h4>
                        </div>
                        <div class="col-4" id="cart-total">
                            <h4 class="card-title mb-0">TZS : 0.0</h4>
                        </div>
                    </div>

                </div>
                <div class="card-body" id="product-details">
                    <div id="cart-contents">
                        {% if cart_products|length > 0 %}
                            <table class='table table-bordered' id='cart-table'>
                                <thead><th></th><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></thead>
                                <tbody>
                                    {% for product in cart_products %}
                                        <tr id='{{ product.product_id }}'>
                                            <td>
                                                <a href="{% url 'sales:delete-from-cart' product_id=product.product_id %}">
                                                    <i class="fa fa-trash-alt"></i>
                                                </a>
                                            </td>
                                            <td>{{ product.product_name }}</td>
                                            <td>{{ product.quantity }}</td>
                                            <td>{{ product.unit_price }}</td>
                                            <td class="product_total">{{ product.total }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                        {% else %}
                            <div class="alert alert-info" id="cart-alert">No items, shopping cart is empty</div>
                        {% endif %}
                    </div>
                    <div class="row">
                            <div class="col-6 text-center" id="cart-btns">
                                <a href="{% url 'sales:check-out' %}" class="btn btn-info">
                                    Check-out <i class="fa fa-flag-checkered"></i>
                                </a>
                            </div>
                            <div class="col-6 text-center">
                                <a href="{% url 'sales:clear-cart' %}" class="btn btn-outline-danger">Empty Cart
                                    <i class="fa fa-flag-checkered"></i>
                                </a>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>

    <script>

    $("#sales_form").submit(function () {

       let formData = $("#sales_form").serialize();

       $("input#product-search").val('');

       $.ajax({
           url: "{% url 'sales:add-to-cart' %}",
           data: formData,
           method: 'POST',
           success: function(reply){

               if(reply.error) {
                   $('#cart-contents').html(reply.error);
               }else {

                   $('#cart-contents').html('');

                   $('#cart-contents').append("<table class='table table-bordered' id='cart-table'></table>");

                   $('#cart-table').append("<th></th><th>Item</th><th>Qty</th><th>Price</th><th>Total</th>");

                   let cart_total = 0;

                   reply.forEach(function (item) {

                       cart_total = cart_total + parseInt(item.total);

                       $('#cart-table').append("<tr id='" + item.product_id + "'></tr>");
                       $("tr#" + item.product_id).append("<td><a href='/sales/delete-from-cart/"+item.product_id+"/'><i class='fa fa-trash'></i></a><td>" + item.product_name + "</td><td>" + item.quantity + "</td><td>" + item.unit_price + "</td><td>" + item.total + "</td>");

                       $('#cart-total').html("<h4 class='card-title mb-0'>TZS : " + cart_total + "</h4>");
                   });
               }
           }
       });

       return false;
    });

    let options = {

        url: "{% url 'sales:search-products' %}?product=" + $("#product-search").val(),

        getValue: "name",

        template: {
            type: "description",
            fields: {
                description: "name"
            }
        },

        list: {
            match: {
                enabled: true,
            },
            onChooseEvent: function() {
                $("input#quantity").val(1);

                $("#search-instructions").hide(1000);
                $("#sales_form").show();

                let name = $("#product-search").getSelectedItemData().name;
                let quantity = $("#product-search").getSelectedItemData().quantity;
                let product_id = $("#product-search").getSelectedItemData().id;

                let retail_price = $("#product-search").getSelectedItemData().retail_price;
                let buying_price = $("#product-search").getSelectedItemData().buying_price;

                $("#product_name").html(name);

                $("input#quantity").attr("value", 1); //default qty is 1
                $("input#quantity").attr("max", parseInt(quantity)); //limit selling more than what is in store (works client-side only)

                $("input#unit_price").attr("value", retail_price); //default unit retail_price
                $("input#unit_price").attr("min", buying_price); //prevent selling item below buying price
                $("input#total").attr("value", retail_price); //default qty x price
                $("input#product_pk").attr("value", product_id);
                $("input#product").attr("value", name);

            }
        },

        theme: "plate-dark"
    };

    $("#product-search").easyAutocomplete(options);

    $("input#quantity").change(function () { // update total price when qty changes

        let qty = $("input#quantity").val();
        let price = $("input#unit_price").val();

        let total = qty * price;

        $("input#total").attr("value", total); //default qty x price
    });

    $("input#unit_price").keyup(function () { // update total price when unit price changes

        let qty = $("input#quantity").val();
        let price = $("input#unit_price").val();

        let total = qty * price;

        $("input#total").attr("value", total); //default qty x price
    });

    $(document).ready(function () {

        let cart_total = 0.0;
        let product_totals = document.getElementsByClassName('product_total');

        let i;
        for (i = 0; i < product_totals.length; i++) {
            cart_total += parseFloat(product_totals[i].textContent);
        }

        $('#cart-total').html("<h4 class='card-title mb-0'>TZS: "+cart_total+"</h4>");

    });


    </script>
{% endblock page_content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="{{ message.tags }} alert-dismissible" id="" role="alert" {% endif %}>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"> &times; </span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} {% endif %}
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

templates/sidebar.html
<nav id="sidebar">
        <div class="sidebar-header">
            <h3>SUPERCOM POS</h3>
            <strong>POS</strong>
        </div>

        <ul class="list-unstyled components">
            <li class="sidebar-li">
                <a href="{% url 'home' %}"><i class="fas fa-home"></i> Home</a>
            </li>
            <li class="sidebar-li">
                <a href="#productsSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-shopping-basket"></i> Products
                </a>
                <ul class="collapse list-unstyled" id="productsSubmenu">
                    <li>
                        <a href="{% url 'products:home' %}">
                            <i class="fa fa-list"></i> View Categories</a> 
                    </li>
                    <li>
                        <a href="{% url 'products:add-categories' %}">
                            <i class="fa fa-list"></i> Add Categories</a> 
                    </li>
                    <li>
                        <a href="{% url 'products:home' %}">
                            <i class="fa fa-list"></i> View Products</a> 
                    </li>
                    <li>
                         <a href="{% url 'products:create-product' %}">
                             <i class="fa fa-shopping-bag"></i> Add New Product</a> 
                    </li>
                    <li>
                         <a href="{% url 'deliveries:home' %}">
                             <i class="fa fa-shopping-basket"></i> Deliveries</a> 
                    </li>
                    <li>
                         <a href="{% url 'products:view-transfers' %}">
                             <i class="fa fa-shopping-basket"></i> Transfers</a> 
                    </li>
                </ul>
            </li>
            <li class="sidebar-li">
                <a href="#salesSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-handshake"></i> Sales
                </a>
                <ul class="collapse list-unstyled" id="salesSubmenu">
                    <li>
                        <a href="{% url 'sales:home' %}">
                            <i class="fa fa-list"></i> POS
                        </a> 
                    </li>
                    <li>
                          <a href="{% url 'sales:reports-home' %}">
                             <i class="fa fa-shopping-bag"></i> Reports</a> 
                    </li>
                    <li>
                          <a href="{% url 'returns:home' %}">
                             <i class="fa fa-shopping-bag"></i> Returns</a>
                    </li>
                </ul>
            </li>
            
            <li class="sidebar-li">
                <a href="#customersSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-handshake"></i> Customers
                </a>
                <ul class="collapse list-unstyled" id="customersSubmenu">
                    <li>
                        <a href="{% url 'customers:home' %}">
                            <i class="fa fa-list"></i> View
                        </a> 
                    </li>
                    <li>
                         <a href="{% url 'customers:create-customer' %}">
                             <i class="fa fa-shopping-bag"></i> Add New</a> 
                    </li>
                </ul>
            </li>
            <li class="sidebar-li">
                <a href="#suppliersSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-truck"></i> Suppliers
                </a>
                <ul class="collapse list-unstyled" id="suppliersSubmenu">
                    <li>
                        <a href="{% url 'suppliers:home' %}">
                            <i class="fa fa-list"></i> View</a> 
                    </li>
                    <li>
                         <a href="{% url 'suppliers:create-supplier' %}">
                             <i class="fa fa-user-plus"></i> Add New
                         </a> 
                    </li>
                </ul>
            </li>
            <li class="sidebar-li">
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-users"></i> Staff
                </a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="{% url 'staff:home' %}">
                            <i class="fa fa-list"></i> View</a> 
                    </li>
                    <li>
                        <a href="{% url 'staff:create-staff' %}">
                            <i class="fa fa-user-plus"></i> Add New</a> 
                    </li>
                </ul>
            </li>
            <li class="sidebar-li">
                <a href="#systemSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-cog"></i> Expense
                </a>
                <ul class="collapse list-unstyled" id="systemSubmenu">
                    <li>
                        <a href="{%  url 'expense:add-expesne' %}">
                            <i class="fa fa-cog"></i> Add Expense </a>
                    </li>
                    {% if request.user.is_superuser %}
                
                    <li>
                        <a href="{%  url 'expense:expense-report' %}">
                            <i class="fa fa-cog"></i> Report </a>
                    </li>
                    <li>
                        <a href="{%  url 'expense:expesne' %}">
                            <i class="fa fa-cog"></i> Expense </a>
                    </li>
                    <li>
                        <a href="{%  url 'expense:profit-loss-report'%}">
                            <i class="fa fa-cog"></i> Profit & Loss Report </a>
                    </li>
                    {% endif %}
                   
                </ul>
            </li> 
            <li class="sidebar-li">
                <a href="#systemSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-cog"></i> System 
                </a>
                <ul class="collapse list-unstyled" id="systemSubmenu">
                    <li>
                         <a href="{% url 'branches:home' %}">
                            <i class="fa fa-code-branch"></i> Branches</a> 
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-cog"></i> Administration </a>
                    </li>
                 
                </ul>
            </li>
            
        </ul>

    </nav>

templates/top-navigation.html
<nav class="navbar navbar-expand-lg" style="background: #17a2b4;">
    <button type="button" id="sidebarCollapse" class="btn btn-info btn-sm rounded">
        <i class="fa fa-bars navbar-toggler-icon"></i>
    </button>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                 <a class="nav-link" href="{% url 'sales:home' %}">
                    POS <span class="text-white">
                    {% if request.user.branch %}
                        @{{ request.user.branch.name|truncatechars:20 }}
                    {% endif %}</span>
                </a> 
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user" style="color:rd"></i> <strong>{{ request.user.last_name }}</strong>
                    </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{% url 'staff:update-staff' pk=request.user.pk %}">My Profile</a>
                          <a class="dropdown-item" href="{% url 'staff:change-branch' %}">Change branch</a> 
                          <a class="dropdown-item" href="{% url 'staff:logout' %}">Logout</a>
                        </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'staff:login' %}">
                        <i class="fa fa-sign-in-alt"></i> Login
                    </a>
                </li>
            {% endif %} 
        </ul>
    </div>

</nav>