deliveries/urls.py
from django.urls import path
from deliveries import views

app_name = 'deliveries'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('set-supplier/', views.SetSupplier.as_view(), name='set-supplier'),
    path('search-product/', views.SearchProduct.as_view(), name='search-product'),
    path('create-delivery-note/', views.CreateDeliveryNote.as_view(), name='create-delivery-note'),
    path('post-stock/', views.PostStock.as_view(), name='post-stock'),
    path('clear-delivery-note/', views.ClearDeliveryNote.as_view(), name='clear-delivery-note'),
    path('list-delivery-items/<int:delivery_id>/', views.ListDeliveryItems.as_view(), name='list-delivery-items'),
]

home/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    ]
    

pos/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('suppliers/', include('suppliers.urls', namespace='suppliers')),
    path('customers/', include('customers.urls',namespace='customers')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('branches/', include('branches.urls', namespace='branches')),
    path('products/', include('products.urls', namespace='products')),
    path('sales/', include('sales.urls', namespace='sales')),
    path('deliveries/', include('deliveries.urls', namespace='deliveries')),
    path('returns/', include('returns.urls', namespace='returns')),
    path('expense/', include('expesne.urls', namespace='expense')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('create-product/', views.CreateProduct.as_view(), name='create-product'),
    path('update-product/<int:pk>/', views.UpdateProduct.as_view(), name='update-product'),
    path('delete-product/<int:pk>/', views.DeleteProduct.as_view(), name='delete-product'),
    path('product-detail/<int:pk>', views.ProductDetail.as_view(), name='product-detail'),
    path('view-transfers/', views.ViewTransfers.as_view(), name='view-transfers'),
    path('transfer-products/', views.TransferProducts.as_view(), name='transfer-products'),
    path('view-transfer-products/<int:transfer_id>', views.ViewTransferProducts.as_view(), name='view-transfer-products'),
    path('add-product/', views.AddProduct.as_view(), name='add-product'),
    path('delete-cart-product/<int:product_id>/', views.DeleterCartProduct.as_view(), name='delete-cart-product'),
    path('clear-list/', views.ClearList.as_view(), name='clear-list'),
    path('set-transfer-to/', views.SetTransferTo.as_view(), name='set-transfer-to'),
    path('process-transfer/', views.ProcessTransfer.as_view(), name='process-transfer'),
    path('receive-transfer/<int:transfer_id>/', views.ReceiveTransfer.as_view(), name='receive-transfer'),
    path('add-category', views.CreateCategory.as_view(), name='add-categories'),

]

suppliers/urls.py
from django.urls import path
from suppliers import views

app_name = 'suppliers'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('add-new/', views.CreateSupplier.as_view(), name='create-supplier'),
    path('update-supplier/<int:pk>', views.UpdateSupplier.as_view(), name='update-supplier'),
    path('delete-supplier/<int:pk>', views.DeleteSupplier.as_view(), name='delete-supplier'),
]

home/models.py
def delivery_value(products_list):

    del_val = 0

    for item in products_list:

        del_val += item['total_cost']

    return del_val

deliveries/forms.py
from django import forms
from suppliers.models import Supplier
from branches.models import Branch

class DeliveriesFiltersForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['date_from'].widget.attrs.update({'class': 'form-control'})
        self.fields['date_from'].widget.attrs.update({'placeholder': 'Date from'})
        self.fields['date_to'].widget.attrs.update({'class': 'form-control'})
        self.fields['date_to'].widget.attrs.update({'placeholder': 'Date to'})
        self.fields['branch'].widget.attrs.update({'class': 'form-control'})
        self.fields['date_from'].widget.attrs.update({'id': 'date_from'})
        self.fields['date_to'].widget.attrs.update({'id': 'date_to'})

    date_from = forms.DateField()
    date_to = forms.DateField()
    branch = forms.ModelChoiceField(
        queryset=Branch.objects.all(),
    )


class DeliveryForm(forms.Form):
    product = forms.CharField()
    quantity = forms.IntegerField()
    buying_price = forms.FloatField(initial=0.0)
    retail_price = forms.FloatField(initial=0.0)
    wholesale_price = forms.FloatField(initial=0.0)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['product'].widget.attrs.update({'class': 'form-control'})
        self.fields['product'].widget.attrs.update({'id': 'product_id'})
        self.fields['quantity'].widget.attrs.update({'class': 'form-control'})
        self.fields['quantity'].widget.attrs.update({'min': '1'})
        self.fields['buying_price'].widget.attrs.update({'class': 'form-control'})
        self.fields['buying_price'].widget.attrs.update({'min': '1'})
        self.fields['wholesale_price'].widget.attrs.update({'class': 'form-control'})
        self.fields['wholesale_price'].widget.attrs.update({'min': '1'})
        self.fields['retail_price'].widget.attrs.update({'class': 'form-control'})
        self.fields['retail_price'].widget.attrs.update({'min': '1'})


class SetSupplierForm(forms.Form):
    supplier = forms.ModelChoiceField(queryset=Supplier.objects.all())
    delivery_number = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['supplier'].widget.attrs.update({'class': 'form-control'})
        self.fields['delivery_number'].widget.attrs.update({'class': 'form-control'})


class ReceiveDeliveryForm(forms.Form):
    product = forms.CharField(max_length=150)
    quantity = forms.IntegerField(initial=1)
    buying_price = forms.FloatField(initial=0.0)
    retail_price = forms.FloatField(initial=0.0)
    wholesale_price = forms.FloatField(initial=0.0)
    received_from = forms.CharField(max_length=150)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['product'].widget.attrs.update({'class': 'form-control'})
        self.fields['quantity'].widget.attrs.update({'class': 'form-control'})
        self.fields['buying_price'].widget.attrs.update({'class': 'form-control'})
        self.fields['retail_price'].widget.attrs.update({'class': 'form-control'})
        self.fields['wholesale_price'].widget.attrs.update({'class': 'form-control'})
        self.fields['received_from'].widget.attrs.update({'class': 'form-control'})

deliveries/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import ListView, FormView, TemplateView
from deliveries.models import Delivery, Stock
from deliveries.forms import SetSupplierForm, DeliveryForm, DeliveriesFiltersForm
from products.models import Product, BranchProduct
from suppliers.models import Supplier
import json
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.contrib import messages
from deliveries.utils import delivery_value


class ListDeliveryItems(PermissionRequiredMixin, ListView):
    permission_required = ["delivery.view_delivery"]
    raise_exception = True
    permission_denied_message = "You dont have permission to view deliveries"
    template_name = "deliveries/delivery_items.html"
    model = Stock
    context_object_name = "stock_list"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        stock_queryset = Stock.objects.filter(delivery_id=self.kwargs['delivery_id'])
        delivery = get_object_or_404(Delivery, pk=self.kwargs['delivery_id'])
        stock = list()
        num = 0

        for item in stock_queryset:

            total_cost = item.quantity * item.buying_price
            num += 1

            stock.append({
                "num": num,
                "product_id": item.product_id,
                "product_name": item.product.name,
                "buying_price": item.buying_price,
                "quantity": item.quantity,
                "total_cost": total_cost
            })

        context['stock_list'] = stock
        context['delivery'] = delivery

        return context


class PostStock(PermissionRequiredMixin, TemplateView):
    """Saves data to the database"""
    permission_required = ['delivery.add_delivery']
    raise_exception = True
    permission_denied_message = "You dont have permission to add delivery"

    def get(self, request, *args, **kwargs):

        try:
            products = request.session['products']
        except KeyError:

            messages.error(request, "No products have been added", extra_tags="alert alert-danger")

            return redirect(to="/deliveries/create-delivery-note/")

        supplier = get_object_or_404(Supplier, pk=request.session['supplier']['supplier_id'])
        del_val = delivery_value(products)

        delivery = Delivery(
            received_from_id=supplier.pk,
            processed_by_id=request.user.pk,
            branch_id=request.user.branch.pk,
            value=del_val,
            delivery_number=request.session['supplier']['delivery_number']
        )

        delivery.save()

        for item in products:

            product = get_object_or_404(Product, pk=item['product_id'])

            product.quantity = product.quantity + item['quantity']

            product.save()

            stock = Stock(
                product_id=product.pk,
                quantity=item['quantity'],
                buying_price=item['buying_price'],
                retail_price=item['retail_price'],
                wholesale_price=item['wholesale_price'],
                current_branch_id=request.user.branch.pk,
                home_branch_id=request.user.branch.pk,
                delivery_id=delivery.pk,
                staff_id=request.user.pk
            )

            stock.save()

            # Update branch_stock tbl

            branch_stock, created = BranchProduct.objects.get_or_create(
                product_id=product.pk,
                branch_id=request.user.branch.pk
            )

            branch_stock.quantity = branch_stock.quantity + item['quantity']

            branch_stock.save()

        messages.success(request, "Success, products stock has been updated.", extra_tags="alert alert-success")

        del request.session['products']
        del request.session['supplier']

        return redirect(to="/deliveries/")


class CreateDeliveryNote(PermissionRequiredMixin, FormView):
    permission_required = ['delivery.add_delivery']
    raise_exception = True
    permission_denied_message = "You dont have permission to add delivery"
    template_name = "deliveries/create_delivery_note.html"
    form_class = DeliveryForm

    def get(self, request, *args, **kwargs):

        context = super().get_context_data(**kwargs)

        if "supplier" not in request.session.keys():

            return redirect(to="/deliveries/set-supplier/")

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):

        form = DeliveryForm(data=request.POST)

        context = self.get_context_data(**kwargs)

        if "products" not in request.session.keys():

            messages.error(request, "Set the supplier to proceed", extra_tags="alert alert-danger")

            return redirect(to="/deliveries/set-supplier/")

        products_list = request.session['products']
        product_ids = [pk['product_id'] for pk in products_list]

        if form.is_valid():

            product = get_object_or_404(Product, pk=form.cleaned_data['product'])

            if len(products_list) == 0:  # add initial product

                num = len(products_list) + 1
                products_list.append({
                    "num": num,
                    "product_name": product.name,
                    "product_id": product.pk,
                    "quantity": form.cleaned_data['quantity'],
                    "buying_price": form.cleaned_data['buying_price'],
                    "retail_price": form.cleaned_data['retail_price'],
                    "wholesale_price": form.cleaned_data['wholesale_price'],
                    "total_cost": form.cleaned_data['buying_price'] * form.cleaned_data['quantity'],
                })
            else:  # products_list has items, loop through

                if product.pk not in product_ids:
                    num = len(products_list) + 1

                    products_list.append({
                        "num": num,
                        "product_name": product.name,
                        "product_id": product.pk,
                        "quantity": form.cleaned_data['quantity'],
                        "buying_price": form.cleaned_data['buying_price'],
                        "retail_price": form.cleaned_data['retail_price'],
                        "wholesale_price": form.cleaned_data['wholesale_price'],
                        "total_cost": form.cleaned_data['buying_price'] * form.cleaned_data['quantity'],
                    })
                else:

                    for item in products_list:

                        if item['product_id'] == product.pk:

                            item['quantity'] = form.cleaned_data['quantity']
                            item['buying_price'] = form.cleaned_data['buying_price']
                            item['retail_price'] = form.cleaned_data['retail_price']
                            item['wholesale_price'] = form.cleaned_data['wholesale_price']
                            item['total_cost'] = form.cleaned_data['buying_price'] * form.cleaned_data['quantity']

            request.session['products'] = products_list

            return redirect(to="/deliveries/create-delivery-note/")

        else:  # form is invalid

            request.session['products'] = products_list

        context['products_list'] = request.session['products']

        return render(request, self.template_name, context=context)


class SetSupplier(PermissionRequiredMixin, FormView):
    permission_required = ["delivery.add_delivery"]
    raise_exception = True
    permission_denied_message = "You dont have permission to add deliveries"
    template_name = "deliveries/set_supplier.html"
    form_class = SetSupplierForm

    def post(self, request, *args, **kwargs):

        form = self.form_class(data=request.POST)

        if form.is_valid():

            supplier = form.cleaned_data['supplier']

            request.session['supplier'] = {
                "supplier_id": supplier.pk,
                "supplier_name":supplier.name,
                "delivery_number": form.cleaned_data['delivery_number']
            }
            request.session['products'] = list()

        return redirect(to='/deliveries/create-delivery-note')


class SearchProduct(PermissionRequiredMixin, FormView):
    permission_required = ["deliveries.create_delivery"]
    raise_exception = True
    permission_denied_message = "You dont have permission to add deliveries"

    def get(self, request, *args, **kwargs):

        try:

            products = Product.objects.filter(name__contains=request.GET.get('product'))

            product_list = []

            for item in products:

                product_list.append({"product_name": item.name, "product_id": item.pk, "description": item.description})

            response = json.dumps(product_list)

        except ObjectDoesNotExist as exp:

            err_str = str(exp) + str(" or not active")

            response = json.dumps({'err': err_str})

        return HttpResponse(response, content_type="text/json")


class ClearDeliveryNote(PermissionRequiredMixin, TemplateView):
    permission_required = ['delivery.add_delivery']
    raise_exception = True
    permission_denied_message = "You dont have permission to add deliveries"

    def get(self, request, *args, **kwargs):

        if 'products' in request.session.keys():

            del request.session['products']
        else:
            pass

        return redirect(to='/deliveries/create-delivery-note/')


class Home(PermissionRequiredMixin, FormView):
    """Displays deliveries and filters deliveries based on submitted form"""

    permission_required = ['delivery.view_delivery']
    raise_exception = True
    permission_denied_message = "You dont have permission to view deliveries"
    form_class = DeliveriesFiltersForm

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from suppliers.models import Supplier
from django.contrib.auth.mixins import PermissionRequiredMixin


class Home(PermissionRequiredMixin, TemplateView):

    template_name = 'home.html'
    permission_denied_message = "You dont have permission to access page"

    def has_permission(self):

        if self.request.user.is_staff or self.request.user.is_superuser:

            return True
        else:
            return False

templates/deliveries/create_delivery_note.html
{% extends 'base.html' %}
{% block title %}Process Delivery Note{% endblock title %}

{% load static %}

{% block page_style %}
		<link href="{% static 'autocomplete/easy-autocomplete.min.css' %}" rel="stylesheet" type="text/css">
        <style>
            th{background-color: rgb(233, 236, 239);}
            .fa-trash-alt, .fa-trash{color: red;}
        </style>
{% endblock page_style %}

{% block page_js %}
    <script src="{% static 'autocomplete/jquery-1.11.2.min.js' %}"></script>
	<script src="{% static 'autocomplete/jquery.easy-autocomplete.min.js' %}" type="text/javascript" ></script>
{% endblock page_js %}

{% block page_content %}
    <nav class="navbar navbar-expand-lg context-bar">
      <a class="navbar-brand" href="#">
          <i class="fa fa-users"></i> Delivery Note
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{% url 'deliveries:home' %}">
              <i class="fa fa-list-ul"></i> View Deliveries
          </a>
        </div>
      </div>
    </nav>

    {% include 'messages.html' %}

    <div class="card ">
        <div class="card-header">
            <h4 class="card-title m-0">Processing delivery from {{ request.session.supplier.supplier_name }}</h4>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-4">
                    <form method="post" action="{% url 'deliveries:create-delivery-note' %}">{% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-block btn-info"> Add </button>
                        <button type="reset" id="reset-btn" class="btn btn-outline-dark btn-block">Reset form</button>
                        <a href="{% url 'deliveries:set-supplier' %}" class="btn btn-link btn-block">Change Supplier</a>
                    </form>
                </div>
                <div class="col-8">
                    {% if request.session.products|length > 0 %}

                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <th>#</th><th>Name</th><th>Qty</th><th>Buying</th><th>Retail</th><th>Wholesale</th><th>Total</th>
                            </thead>
                            <tbody>
                                {% for product in request.session.products %}
                                    <tr>
                                        <td>{{ product.num }}.</td>
                                        <td>{{ product.product_name }}</td>
                                        <td>{{ product.quantity }}</td>
                                        <td class="text-right">{{ product.buying_price }}</td>
                                        <td class="text-right">{{ product.retail_price }}</td>
                                        <td class="text-right">{{ product.wholesale_price }}</td>
                                        <td class="product_total text-right">{{ product.total_cost }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                               <tr class="text-center">
                                   <td colspan="3" id="cart-total">
                                       Total <span class="badge badge-pill badge-danger">0.0</span>
                                   </td>
                                   <td>
                                       <a href="{% url "deliveries:clear-delivery-note" %}">
                                           Clear <i class="fa fa-trash"></i>
                                       </a>
                                   </td>
                                   <td colspan="3" style="border-right: none;">
                                       <a href="{% url 'deliveries:post-stock' %}" class="btn btn-info text-right">Post Products</a>
                                   </td>
                               </tr>
                            </tfoot>
                        </table>
                    {% else %}
                        <div class="alert alert-info">No items in this delivery note, add items from the left.</div>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript">
        $("button#reset-btn").click(function (e) {
            $("input#product_id").attr("readonly", false);
        });
        let options = {

            url: "{% url 'deliveries:search-product' %}?product=" + $("#product_id").val(),

            getValue: "product_name",

            template: {
                type: "description",
                fields: {
                    description: "product_name"
                }
            },

            list: {
                match: {enabled: true,},
                onChooseEvent: function() {
                    let product_name = $("#product_id").getSelectedItemData().product_name;
                    let product_id = $("#product_id").getSelectedItemData().product_id;

                    $("input#product_id").val(product_id);
                    $("input#product_id").attr("readonly", true);

                    $("label[for='product_id']").html("Product: <strong style='color: black;'>"+product_name+"</strong>");
                }
            },

            theme: "plate-dark"
        };

    $("#product_id").easyAutocomplete(options);

    $(document).ready(function () {

        let cart_total = 0.0;
        let product_totals = document.getElementsByClassName('product_total');

        let i;
        for (i = 0; i < product_totals.length; i++) {
            cart_total += parseFloat(product_totals[i].textContent);
        }

        $('#cart-total').html("<h4 class='card-title mb-0'>Total : "+cart_total+"</h4>");

    });
    </script>

{% endblock page_content %}

templates/deliveries/delivery_items.html
{% extends 'base.html' %}

{% block title %}Delivery {{ delivery.delivery_number }} from {{ delivery.received_from.name }} on {{ delivery.date|date:"d-m-Y" }}{% endblock title %}

{% load static %}

{% block page_content %}
    <nav class="navbar navbar-expand-lg context-bar">
      <a class="navbar-brand" href="#">
          <i class="fa fa-users"></i> Delivery {{ delivery.delivery_number }} from {{ delivery.received_from.name }}
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{% url 'deliveries:home' %}">
              <i class="fa fa-plus-circle"></i> View Deliveries
          </a>
        </div>
      </div>
    </nav>

    {% include 'messages.html' %}
    <form method="post">{% csrf_token %}
        <div class="form-row">
            <div class="col"></div>
        </div>
    </form>
    <div class="row">
        <div class="col-9">
            <div class="card ">
                <div class="card-body">
                    {% if stock_list|length > 0 %}

                        <table class="table table-striped table-bordered table-hover table-sm" id="myTable">
                            <thead class="bg-light">
                                <th>#</th><th>Item</th><th>Qty</th><th>Buying</th><th>Total</th>
                            </thead>
                            <tbody>
                                {% for item in stock_list %}
                                    <tr>
                                        <td>{{ item.num }}</td>
                                        <td>
                                            <a href="{% url 'products:product-detail' pk=item.product_id %}"> {{ item.product_name }} </a>
                                        </td>
                                        <td>{{ item.quantity }}</td>
                                        <td class="text-right">{{ item.buying_price }}</td>
                                        <td class="text-right">{{ item.total_cost }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <div class="alert alert-info">Delivery {{ delivery.delivery_number }} has no items</div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card text-white bg-light text-dark">
{#              <div class="card-header"><h5 class="card-title text-center mb-0">At a Glance</h5></div>#}
              <div class="card-body  p-0">
                <table class="table table-responsive mb-0">
                    <tr><td style="background: #eeeeee;">Supplier</td><td>{{ delivery.received_from.name }}</td></tr>
                    <tr><td style="background: #eeeeee;">Number</td><td>{{ delivery.delivery_number }}</td></tr>
                    <tr><td style="background: #eeeeee;">Date</td><td>{{ delivery.date }}</td></tr>
                    <tr><td style="background: #eeeeee;">Value</td><td>{{ delivery.value }}</td></tr>
                    <tr><td style="background: #eeeeee;">Staff</td><td>{{ delivery.processed_by.get_full_name }}</td></tr>
                </table>
              </div>
            </div>
        </div>
    </div>

{% endblock page_content %}

templates/deliveries/set_supplier.html
{% extends 'base.html' %}
{% block title %}Set Supplier{% endblock title %}
{% block page_content %}
    <nav class="navbar navbar-expand-lg context-bar">
      <a class="navbar-brand" href="#">
          <i class="fa fa-truck-loading"> </i> Set Supplier
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{% url 'deliveries:home' %}">
              <i class="fa fa-plus-circle"></i> View Deliveries
          </a>
        </div>
      </div>
    </nav>

    {% include 'messages.html' %}

    <div class="card ">
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    <form action="{% url 'deliveries:set-supplier' %}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p class="p-4">
                            <button type="submit" class="btn btn-info btn-block">
                                Next <i class="fa fa-arrow-right"></i>
                            </button>
                        </p>
                    </form>
                </div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-body" style="background-color: #eee;">
                            Set the supplier and click next to start processing the delivery.
                            To create a new supplier, <a href="{% url 'suppliers:create-supplier' %}">click here</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock page_content %}